In [2]:
import numpy as np

In [54]:
a=np.array([1,2,3,4,5,6])
b=np.array([7,8,9,10,11,12])
c=np.concatenate([a,b])
d=np.concatenate((a,b))

In [40]:
print(a)
print(b)
print(c)
print(d)

[1 2 3 4 5 6]
[ 7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [39]:
n=np.array_split(a,5)
m=np.vsplit(a,3)
print(n)
print(m)

ValueError: vsplit only works on arrays of 2 or more dimensions

In [70]:
a=np.array([[1,22,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
c=np.concatenate((a,b),axis=0)
d=np.concatenate((a,b),axis=-1)

print(c.shape)
print(d.shape)

(4, 3)
(2, 6)


In [71]:
print(np.sort(a,axis=1))

[[ 1  3 22]
 [ 4  5  6]]


In [26]:
n=np.array_split(a,3,axis=1)
print(n)

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [27]:
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
b=np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])
c=np.concatenate((a,b),axis=0)
d=np.concatenate((a,b),axis=1)
e=np.concatenate((a,b),axis=2)

In [32]:
n=np.array_split(a,3,axis=1)
print(n)

[array([[[1, 2, 3]],

       [[7, 8, 9]]]), array([[[ 4,  5,  6]],

       [[10, 11, 12]]]), array([], shape=(2, 0, 3), dtype=int64)]


In [31]:
print(a)
print(b)
print(c)
print(d)
print(e)
print(c.shape)
print(d.shape)
print(e.shape)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[[[  1   2   3]
   [  4   5   6]]

  [[  7   8   9]
   [ 10  11  12]]]


 [[[ 10  20  30]
   [ 40  50  60]]

  [[ 70  80  90]
   [100 110 120]]]]
(4, 3)
(2, 6)
(2, 2, 2, 3)


In [35]:
e=np.dstack((a,b))
print(e)
print(e.ndim)
print(e.shape)

[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]
3
(2, 3, 2)


In [57]:
j=np.array([1,2,3,4,5,5])


In [63]:
x=np.searchsorted(j,0)
print(x)

0


In [66]:
n=np.array([1,6,85,24,6,12,645])
print(np.sort(n))
print(n)

[  1   6   6  12  24  85 645]
[  1   6  85  24   6  12 645]


In [77]:
k=[]
for i in n:
    if i>12:
        k.append(True)
    else:
        k.append(False)
x=n[k]

In [78]:
print(x)

[ 85  24 645]


In [79]:
k=n>12
x=n[k]
print(x)

[ 85  24 645]
